---
title: "Class 12: Bioinformatics in drug discovery and design"
author: "Yi Fu"
date: "5/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First, let's check if "bio3d" package is installed. And then, load the package.
```{r include=FALSE}
if (!require("bio3d")) {
  install.packages("bio3d")
}
```

```{r}
library(bio3d)
```

```{r}
file.name <- get.pdb("1hsg.pdb")
hiv <- read.pdb(file.name)
```

```{r}
prot <- atom.select(hiv, "protein",value=T)
lig <- atom.select(hiv, "ligand",value=T)
write.pdb(prot, file="1hsg_protein.pdb")
write.pdb(lig, file="1hsg_ligand.pdb")
```

```{bash}
#~/Downloads/autodock_vina_1_1_2_mac/bin/vina --config config.txt --log log.txt
```

## process our docking results
```{r}
res <- read.pdb("all.pdbqt", multi=T)
write.pdb(res, "results.pdb")
```

##  calculate the RMSD (root mean square distance) between each of the docking results and the known crystal structure using the bio3d package.
```{r}
# res <- read.pdb("all.pdbqt", multi=TRUE)
ori <- read.pdb("1hsg_ligand.pdbqt")
rmsd(ori, res)
```


## Normal Mode analysis for flexibility prediction
```{r}
pdb <- read.pdb("1HEL")
modes <- nma(pdb)
plot(modes, sse=pdb)
mktrj(modes, mode=7, file="nma_7.pdb")
```

